name: "Forrest Spotify Currator"
description: "Currate a spotify playlist."
version: "0.0.1"
slug: "forrest_spotify_currator"
homeassistant_api: true
hassio_api: true
hassio_role: default
build_from:
  armhf: python:3.8
arch:
  - armhf
schema:
  playlist_id: str
  client_id: str
  client_secret: str
  username: str
  password: str