name: "Forrest Spotify Currator"
description: "Currate a spotify playlist."
version: "0.0.1"
slug: "forrest_spotify_currator"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
schema:
  playlist_id: str
  client_id: str
  client_secret: str
  username: str
  password: str